### ISSUE TITLE
References displayed incorreclty

### ISSUE THREAD

**Issue by sergey-tihon** [eridem/vscode-nupkg#2]
I hope that `references: '[object Object]'` in not expected representation
```
Metadata:
  id: SwaggerProvider
  version: 0.6.0-alpha1
  title: SwaggerProvider
  authors: Sergey Tihon
  owners: Sergey Tihon
  licenseUrl: 'http://github.com/fsprojects/SwaggerProvider/blob/master/LICENSE.txt'
  projectUrl: 'http://fsprojects.github.io/SwaggerProvider/'
  iconUrl: >-
    https://raw.githubusercontent.com/fsprojects/SwaggerProvider/master/docs/files/img/logo.png
  description: 'F# Type Provider for Swagger'
  summary: 'F# Type Provider for Swagger'
  releaseNotes: '- Target Profile259 profile (Xamarin support)'
  copyright: Copyright 2017
  tags: 'F# fsharp data typeprovider Swagger API REST'
  references: '[object Object]'

Contents:
```

File
[SwaggerProvider.0.6.0-alpha1.nupkg.zip](https://github.com/eridem/vscode-nupkg/files/891018/SwaggerProvider.0.6.0-alpha1.nupkg.zip)
