### ISSUE TITLE
References section mentioned two times

### ISSUE THREAD

**Issue by sergey-tihon** [eridem/vscode-nupkg#5]
```
Metadata:
  id: DynamicsCRMProvider
  version: 0.2.1
  authors: Ross McKinlay; Steffen Forkmann; Sergey Tihon
  owners: Ross McKinlay; Steffen Forkmann; Sergey Tihon
  licenseUrl: 'http://github.com/fsprojects/DynamicsCRMProvider/blob/master/LICENSE.txt'
  projectUrl: 'http://fsprojects.github.io/DynamicsCRMProvider/'
  iconUrl: >-
    https://raw.githubusercontent.com/fsprojects/DynamicsCRMProvider/master/docs/files/img/logo.png
  requireLicenseAcceptance: 'false'
  description: A type provider for Microsoft Dynamics CRM 2011.
  summary: A type provider for Microsoft Dynamics CRM 2011.
  releaseNotes: Bug fix
  copyright: Copyright 2015
  language: en-US
  tags: 'F# fsharp typeproviders dynamics CRM'
  references: '[object Object]'
References:
  - file: Microsoft.Crm.Services.Utility.dll
  - file: FSharp.Data.DynamicsCRMProvider.Runtime.dll
  - file: FSharp.Data.DynamicsCRMProvider.dll
```

File
[DynamicsCRMProvider.0.2.1.nupkg.zip](https://github.com/eridem/vscode-nupkg/files/891276/DynamicsCRMProvider.0.2.1.nupkg.zip)

**Comment by sergey-tihon** [comment]
The same error with `frameworkAssemblies`

```
Metadata:
  id: VSSDK.IDE.12
  version: 12.0.4
  authors: Sam Harwell
  owners: Sam Harwell
  requireLicenseAcceptance: 'false'
  description: >-
    This is a metadata-only package used as a dependency for reference packages
    and extensions that target Visual Studio 2013 and newer.

          If you find this package installed in an extension that is supposed to target Visual Studio 2010 or 2012, use NuGet to uninstall the package and it will report the specific dependencies that are causing the incompatibility.
  summary: Visual Studio 2013+
  tags: vssdk vs2013 vs2015
  frameworkAssemblies: '[object Object]'
Framework Assemblies:
  .NETFramework4.0: System
```
